-- Migration Script: Add Tutor Availability Feature
-- Description: Creates tutor_availability table to store weekly availability schedules
-- Author: Generated by Claude Code
-- Date: 2025-09-08

-- Use the cognio database
USE cognio;

-- Create the tutor_availability table
CREATE TABLE IF NOT EXISTS tutor_availability (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tutor_id INT NOT NULL,
    day_of_week ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NOT NULL,
    start_time TIME NOT NULL COMMENT 'Start time in GMT',
    end_time TIME NOT NULL COMMENT 'End time in GMT', 
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Foreign key constraint
    CONSTRAINT fk_tutor_availability_tutor_id 
        FOREIGN KEY (tutor_id) REFERENCES tutors(id) 
        ON DELETE CASCADE ON UPDATE CASCADE,
        
    -- Ensure no overlapping time slots for the same tutor on the same day
    CONSTRAINT chk_time_order CHECK (start_time < end_time),
    
    -- Index for performance
    INDEX idx_tutor_day (tutor_id, day_of_week),
    INDEX idx_tutor_availability_lookup (tutor_id, day_of_week, is_available)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores tutor weekly availability schedules with times in GMT';

-- Insert sample data for testing (optional - remove if not needed)
-- This creates sample availability for tutor ID 1 if it exists
INSERT IGNORE INTO tutor_availability (tutor_id, day_of_week, start_time, end_time, is_available)
SELECT 1, 'MONDAY', '13:00:00', '21:00:00', TRUE
WHERE EXISTS (SELECT 1 FROM tutors WHERE id = 1)
UNION ALL
SELECT 1, 'TUESDAY', '13:00:00', '21:00:00', TRUE
WHERE EXISTS (SELECT 1 FROM tutors WHERE id = 1)
UNION ALL
SELECT 1, 'WEDNESDAY', '13:00:00', '21:00:00', TRUE
WHERE EXISTS (SELECT 1 FROM tutors WHERE id = 1)
UNION ALL
SELECT 1, 'THURSDAY', '13:00:00', '21:00:00', TRUE
WHERE EXISTS (SELECT 1 FROM tutors WHERE id = 1)
UNION ALL
SELECT 1, 'FRIDAY', '13:00:00', '21:00:00', TRUE
WHERE EXISTS (SELECT 1 FROM tutors WHERE id = 1);

-- Verify the table was created successfully
DESCRIBE tutor_availability;

-- Show sample data count
SELECT COUNT(*) as availability_records FROM tutor_availability;