-- Rollback Script: Remove Tutor Availability Feature
-- Description: Removes tutor_availability table and related data
-- Author: Generated by Claude Code
-- Date: 2025-09-08
-- WARNING: This will permanently delete all availability data!

-- Use the cognio database
USE cognio;

-- Show current record count before deletion
SELECT COUNT(*) as records_to_be_deleted FROM tutor_availability;

-- Drop the tutor_availability table
-- This will also automatically drop the foreign key constraints and indexes
DROP TABLE IF EXISTS tutor_availability;

-- Verify table has been removed
SHOW TABLES LIKE 'tutor_availability';